name: My cicd practice
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "My first CI/CD practice"
        # uses: actions/checkout@v2